/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parrallel.merge.sort;
import static parrallel.merge.sort.SortBenchmark.*;
/**
 *
 * @author Basil
 */
public class Main extends javax.swing.JFrame{
    int[] currentArray;
    int arrayType;
    int algorithm;
    int siz;
    int spee;
    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runButton = new javax.swing.JButton();
        resetArrayButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        benchmarkOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        algorithmsSelector = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ArrayTypeSelector = new javax.swing.JComboBox<>();
        size = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        runBenchmark = new javax.swing.JButton();
        speed = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        visualizerPanel = new parrallel.merge.sort.ArrayVisualizer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        runButton.setBackground(new java.awt.Color(102, 255, 153));
        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        resetArrayButton.setBackground(new java.awt.Color(255, 51, 51));
        resetArrayButton.setText("Reset Array");
        resetArrayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetArrayButtonActionPerformed(evt);
            }
        });

        benchmarkOutput.setEditable(false);
        benchmarkOutput.setColumns(20);
        benchmarkOutput.setRows(5);
        jScrollPane2.setViewportView(benchmarkOutput);

        jLabel1.setText("Algorithm:");

        algorithmsSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MergeSort", "ParrallelMergeSort", "JavaSort" }));

        jLabel2.setText("Array Type");

        ArrayTypeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Random", "Reverse", "Sorted" }));

        size.setModel(new javax.swing.SpinnerNumberModel(100, 100, 1000, 10));
        size.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("Size:");

        runBenchmark.setText("Run Benchmark");
        runBenchmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBenchmarkActionPerformed(evt);
            }
        });

        speed.setModel(new javax.swing.SpinnerNumberModel(10, 0, null, 10));

        jLabel4.setText("Speed:");

        javax.swing.GroupLayout visualizerPanelLayout = new javax.swing.GroupLayout(visualizerPanel);
        visualizerPanel.setLayout(visualizerPanelLayout);
        visualizerPanelLayout.setHorizontalGroup(
            visualizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        visualizerPanelLayout.setVerticalGroup(
            visualizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(algorithmsSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ArrayTypeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetArrayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addComponent(visualizerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(runBenchmark))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetArrayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(algorithmsSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(ArrayTypeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(runBenchmark, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                    .addComponent(visualizerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        if (currentArray == null) {
            System.out.println("Please reset array first!");
            return;
        }

        int delay = (Integer) speed.getValue(); 
        int algorithmIndex = algorithmsSelector.getSelectedIndex();

        // Disable buttons so user doesn't interrupt
        runButton.setEnabled(false);
        resetArrayButton.setEnabled(false);

        // Start the Animation Thread
        Thread animation = new Thread() {
            @Override
            public void run() {

                // Cast the visualizer once
                ArrayVisualizer viz = (ArrayVisualizer) visualizerPanel;

                // === CHANGED LOGIC START ===
                switch (algorithmIndex) {
                    case 0 ->                         {
                            // 1. Sequential Merge Sort
                            sortAlgorithm sorter = new MergeSort(viz, delay);
                            sorter.sort(currentArray);
                        }
                    case 1 ->                         {
                            // 2. Parallel Merge Sort
                            sortAlgorithm sorter = new ParallelMergeSort(viz, delay);
                            sorter.sort(currentArray);
                        }
                    case 2 -> {
                        // 3. Java Built-in Sort (Arrays.sort)
                        java.util.Arrays.sort(currentArray);
                        viz.repaint();
                    }
                    default -> {
                    }
                }
                // === CHANGED LOGIC END ===


                // Re-enable buttons when done
                runButton.setEnabled(true);
                resetArrayButton.setEnabled(true);

            }
        };

        animation.start();
    }//GEN-LAST:event_runButtonActionPerformed

    private void resetArrayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetArrayButtonActionPerformed
        
        int s = (Integer) size.getValue(); // Assuming spinner name is 'size'

        int typeIndex = ArrayTypeSelector.getSelectedIndex();

        switch (typeIndex) {
            case 0 -> // Random
                currentArray = SortBenchmark.generateRandomArray(s);
            case 1 -> // Sorted
                currentArray = SortBenchmark.generateReverseSortedArray(s);
            case 2 -> // Reverse
                currentArray = SortBenchmark.generateSortedArray(s);
        }

        if (visualizerPanel instanceof ArrayVisualizer) {
            ((ArrayVisualizer) visualizerPanel).setArray(currentArray);
        }
    }//GEN-LAST:event_resetArrayButtonActionPerformed

    private void runBenchmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBenchmarkActionPerformed
        benchmarkOutput.setText("");
        final javax.swing.JButton btn = (javax.swing.JButton) evt.getSource();
        btn.setEnabled(false);
        
        benchmarkOutput.append("Starting Benchmark... Please wait.\n");

        Thread worker = new Thread() {

            @Override
            public void run() {
                benchmarkOutput.append("=== SORTING ALGORITHM BENCHMARK ===\n\n");

                int[] sizes = {10_000, 100_000, 1_000_000};
                int runs = 5;

                sortAlgorithm sequential = new MergeSort();
                sortAlgorithm parallel = new ParallelMergeSort();

                for (int i = 0; i < sizes.length; i++) {
                    int size = sizes[i];

                    benchmarkOutput.append("===================================\n");
                    benchmarkOutput.append("Array Size: " + size + "\n");
                    benchmarkOutput.append("===================================\n");

                    // --- RANDOM ARRAY ---
                    benchmarkOutput.append("\n--- RANDOM ARRAY ---\n\n");
                    int[] randomArray = generateRandomArray(size);

                    SortBenchmark.BenchmarkResult seqResultRandom = 
                        SortBenchmark.runBenchmarkWithComparisons(sequential, randomArray, runs);
                    benchmarkOutput.append("Sequential MergeSort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(seqResultRandom.time) + " ms\n");
                    benchmarkOutput.append("  Comparisons: " + 
                        SortBenchmark.formatComparisons(seqResultRandom.comparisons) + "\n\n");
                    

                    SortBenchmark.BenchmarkResult parResultRandom = 
                        SortBenchmark.runBenchmarkWithComparisons(parallel, randomArray, runs);
                    benchmarkOutput.append("Parallel MergeSort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(parResultRandom.time) + " ms\n");
                    benchmarkOutput.append("  Comparisons: " + 
                        SortBenchmark.formatComparisons(parResultRandom.comparisons) + "\n\n");

                    long builtinTimeRandom = benchmarkBuiltinSort(randomArray, runs);
                    benchmarkOutput.append("Arrays.sort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(builtinTimeRandom) + " ms\n");
                    benchmarkOutput.append("  Comparisons: N/A (built-in)\n\n");

                    // --- REVERSE SORTED ARRAY ---
                    benchmarkOutput.append("\n--- REVERSE SORTED ARRAY ---\n\n");
                    int[] reverseArray = generateReverseSortedArray(size);

                    SortBenchmark.BenchmarkResult seqResultReverse = 
                        SortBenchmark.runBenchmarkWithComparisons(sequential, reverseArray, runs);
                    benchmarkOutput.append("Sequential MergeSort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(seqResultReverse.time) + " ms\n");
                    benchmarkOutput.append("  Comparisons: " + 
                        SortBenchmark.formatComparisons(seqResultReverse.comparisons) + "\n\n");

                    SortBenchmark.BenchmarkResult parResultReverse = 
                        SortBenchmark.runBenchmarkWithComparisons(parallel, reverseArray, runs);
                    benchmarkOutput.append("Parallel MergeSort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(parResultReverse.time) + " ms\n");
                    benchmarkOutput.append("  Comparisons: " + 
                        SortBenchmark.formatComparisons(parResultReverse.comparisons) + "\n\n");

                    long builtinTimeReverse = benchmarkBuiltinSort(reverseArray, runs);
                    benchmarkOutput.append("Arrays.sort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(builtinTimeReverse) + " ms\n");
                    benchmarkOutput.append("  Comparisons: N/A (built-in)\n\n");

                    // --- SORTED ARRAY ---
                    benchmarkOutput.append("\n--- SORTED ARRAY ---\n\n");
                    int[] sortedArray = generateSortedArray(size);

                    SortBenchmark.BenchmarkResult seqResultSorted = 
                        SortBenchmark.runBenchmarkWithComparisons(sequential, sortedArray, runs);
                    benchmarkOutput.append("Sequential MergeSort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(seqResultSorted.time) + " ms\n");
                    benchmarkOutput.append("  Comparisons: " + 
                        SortBenchmark.formatComparisons(seqResultSorted.comparisons) + "\n\n");

                    SortBenchmark.BenchmarkResult parResultSorted = 
                        SortBenchmark.runBenchmarkWithComparisons(parallel, sortedArray, runs);
                    benchmarkOutput.append("Parallel MergeSort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(parResultSorted.time) + " ms\n");
                    benchmarkOutput.append("  Comparisons: " + 
                        SortBenchmark.formatComparisons(parResultSorted.comparisons) + "\n\n");

                    long builtinTimeSorted = benchmarkBuiltinSort(sortedArray, runs);
                    benchmarkOutput.append("Arrays.sort:\n");
                    benchmarkOutput.append("  Time: " + toMilliseconds(builtinTimeSorted) + " ms\n");
                    benchmarkOutput.append("  Comparisons: N/A (built-in)\n\n");

                    benchmarkOutput.append("\n");
                    benchmarkOutput.setCaretPosition(benchmarkOutput.getDocument().getLength());
                }

                benchmarkOutput.append("===================================\n");
                benchmarkOutput.append("BENCHMARK COMPLETE\n");
                benchmarkOutput.append("===================================\n");

                btn.setEnabled(true);
            }
        };

        worker.start();
    
    }//GEN-LAST:event_runBenchmarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ArrayTypeSelector;
    private javax.swing.JComboBox<String> algorithmsSelector;
    private javax.swing.JTextArea benchmarkOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resetArrayButton;
    private javax.swing.JButton runBenchmark;
    private javax.swing.JButton runButton;
    private javax.swing.JSpinner size;
    private javax.swing.JSpinner speed;
    private javax.swing.JPanel visualizerPanel;
    // End of variables declaration//GEN-END:variables
}
